server:
  port: 7000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ango_dev
    username: agpostgres
    password: Zxcv123$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
hiber
